name: base
channels:
  - defaults
dependencies:
  - dash==1.4.1
  - dash-bootstrap-components==0.7.2
  - dash-core-components==1.3.1
  - dash-html-components==1.0.1
  - dash-renderer==1.1.2
  - dash-table==4.4.1
  - flask-compress==1.4.0
  - plotly==4.2.0
  - numpy==1.16.4